src/Game.js
src/Round.js
src/Turn.js

Please check that everything is working correctly.

Add Turn class file and modify Game and Round classes

---

data/surveys.js
src/Game.js
test/game-test.js

- Added the necessary export tag to the data file so we have access to that in other classes
- Added and tested a function to find a random number(id) based on the length of the data array
- Added and tested a function to find a random survey based on that generated id
- The function pushes the found survey into 2 different arrays - the current survey and used 
surveys so that we can keep track of which id's have been used so there are no repeats
- Sorts the current array by score/respondants

Start to the Game class code

---

src/css/base.scss
src/index.html

In addition to alignment, I added a few classes to the HTML.

Add basic alignment to DOM

---

src/Player.js
src/Turn.js
test/player-test.js
test/round-test.js
test/turn-test.js

Please review and provide feedback on how to **update player scores**. I am wondering if I am not linking the files together correctly in a simple syntax error. Any other feedback you see would be helpful too. Thanks!

Player turn je

---

src/Game.js
src/Player.js
src/Round.js
src/Turn.js
test/game-test.js
test/player-test.js
test/round-test.js
test/turn-test.js

Co-Authored by: Eric Meldrum <eric.meldrum@gmail.com>
Co-Authored by: Zoe Harvey <zoekharvey@gmail.com>
Co-
Authored by: Edwin Del Bosque <edwindelbosquer@gmail.com>

Restructure files to be connected

---

src/css/base.scss
src/index.html
test/scripts-test.js

It was hard to implement a testing suite for this project based on what we were taught with localStorage.

Add spice test file for scripts.js

---

src/Game.js
src/Round.js
test/game-test.js
test/round-test.js

Co-Authored by: Eric Meldrum <eric.meldrum@gmail.com>

Fix bugs in Round test file

---

src/index.js

Names entered in inputs now will show up on play page

Connect files je

---

src/DOMupdates.js
src/Game.js
src/index.js
test/game-test.js
test/scripts-test.js

Got the first spies test passed and workflow down. The actual dom manipulation isn't working yet because we' don't have an element to change, but the tests are set up and good to go

First dom test

---

src/DOMupdates.js
src/Round.js
src/Turn.js
src/index.html
src/index.js
test/game-test.js
test/turn-test.js

This is appending the current question to the DOM upon clicking 'start game', and appending correct answers to the DOM, in the correct order.

Append to dom

---

src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/Round.js
src/Turn.js
test/fast-money-test.js
test/fast-turn-test.js
test/game-test.js

- Fixed some bugs in our round and turn files
- started working on  Domination round and turn (functionality and tests)

New Changes to Domination Round/Turn

---

src/DOMupdates.js
src/Round.js
src/Turn.js
src/index.js

This is a pretty minor push, and I probably could have just pushed straight to master. It changes the method called to begin a turn (previously it was round.organizeSurveys, now it's round.beginTurn) and makes those methods work the way they should. A few other minor changes as well.

Change organizeSurveys to beginTurn

---

src/DominationTurn.js
src/Game.js
src/RegularRound.js
src/RegularTurn.js
src/Round.js
src/Turn.js
test/DominationRound-test.js
test/DominationTurn-test.js
test/game-test.js
test/round-test.js
test/turn-test.js

I redid the classes and tests needed to make our new inheritance class work. 
A lot of small changes, but all the previously-working tests are back to normal.
Game isn't getting the updated round count, so I'll start working on that.

Multiplier second

---

src/Round.js
src/Turn.js

This branch accomplished a few things: 
1. Prevents the player from submitting the same guess twice.
2. Toggles the player name that displays on the DOM
3. Makes sure that we are getting into the "End Round" if statement when all three correct guesses are entered (this still needs more functionality to display what round it is).
And a few more.

Fix bugs in turn

---

src/Game.js
src/RegularRound.js

Fixed the bug, now passing the round counter!

Pass test for increasing round counter

---

src/DOMupdates.js
src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/RegularRound.js
src/RegularTurn.js
src/Round.js
src/Turn.js
src/index.html
src/index.js
test/DominationRound-test.js
test/DominationTurn-test.js
test/turn-test.js

This (finally!) gets us past Round 1 when all the correct answers are entered, so now we can get into the Domination Round.

Domination

---

src/DOMupdates.js
src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/RegularRound.js
src/RegularTurn.js
src/Round.js
src/Turn.js
src/index.html
src/index.js
test/DominationRound-test.js
test/DominationTurn-test.js
test/turn-test.js

Reverts edwindelbosque/Cowboys-vs-Aliens#37

Revert "Domination" PR

---

src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/Round.js
src/index.js
test/DominationRound-test.js
test/DominationTurn-test.js
test/turn-test.js

Thinking we need to update logic of startDominationRound method, and invoke in round (instead of turn). Then, for each guess, instantiate a new turn so we can have access to multiple surveys. Struggling to  figure that out.

Domination je

---

src/DOMupdates.js
src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/RegularRound.js
src/RegularTurn.js
src/Turn.js
src/css/_round-page.scss
src/index.html
src/index.js

This creates the timer for the Domination round and instantiates new instances of DominationTurn and Round when you get past Round 2. The code isn't super pretty - needs some refactoring to make sure that every method lives where it should, get rid of overly long functions and nested ifs - but it's working. I will continue to work on getting the scores and points to update later this evening.

Domination round 1

---

src/css/base.scss

A little something, a customized cursor to make it look more game-y

Add custom cursor design for game

---

package-lock.json
src/DominationTurn.js
src/Game.js
test/DominationRound-test.js
test/DominationTurn-test.js
test/game-test.js
test/player-test.js
test/round-test.js
test/turn-test.js

Many changes to test file. 
- jQuery window error fixed
-additional tests added to Game and Round

Spy tests je

---

src/DOMupdates.js
src/RegularTurn.js
src/Round.js
src/css/_round-page.scss
src/css/base.scss

changed a few font-sizes and change color above the guess input to the player's color. (red/green)

Improve experience from UI/UX user testing

---

src/DOMupdates.js
src/DominationRound.js
src/DominationTurn.js
src/Game.js
src/RegularRound.js
src/RegularTurn.js
src/Round.js
src/Turn.js
src/index.js

I went through and cleaned and refactored all the files except for the testing files. I removed unnecessary methods, moved any methods shared by child classes to their parent class (RegularTurn and DominationTurn had a few identical methods, which I moved to Turn), removed unused variables, and ran the linter. I didn't touch the testing files, though; those will need a little bit of work.

Clean and refactor

---

test/DominationRound-test.js
test/DominationTurn-test.js
test/game-test.js
test/round-test.js
test/turn-test.js

Testing is complete!
-All methods have tests
-All tests are passing
-Spies utilized
Co-Authored By: Eric Meldrum <eric.meldrum@gmail.com>

Improve test coverage by making sure all methods are being tested
